// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        // return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJYACRgU5hR8kSR4VEsoeRoBK31KuNNo',
    appId: '1:186569298292:web:8c9bf3e842bbc29fec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    authDomain: 'contacts-app-b0616.firebaseapp.com',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
    measurementId: 'G-D8HE08B6EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsck4K8LbLnSDl12CYUuXNPAbxTYZfB7g',
    appId: '1:186569298292:android:76885917e50a0431ec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3GLarbSC2QKx50MQSOw7nt-BcsfS-xU',
    appId: '1:186569298292:ios:afe4def56f72b74bec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
    iosClientId: '186569298292-rs0tid1olafk8g80pn1o072ajv8r30la.apps.googleusercontent.com',
    iosBundleId: 'com.gautam.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3GLarbSC2QKx50MQSOw7nt-BcsfS-xU',
    appId: '1:186569298292:ios:afe4def56f72b74bec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
    iosClientId: '186569298292-rs0tid1olafk8g80pn1o072ajv8r30la.apps.googleusercontent.com',
    iosBundleId: 'com.gautam.contacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnJYACRgU5hR8kSR4VEsoeRoBK31KuNNo',
    appId: '1:186569298292:web:ecacaf9c27ad7df8ec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    authDomain: 'contacts-app-b0616.firebaseapp.com',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
    measurementId: 'G-SJL37XNNXE',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAnJYACRgU5hR8kSR4VEsoeRoBK31KuNNo',
    appId: '1:186569298292:web:62a1260e6202982dec5c21',
    messagingSenderId: '186569298292',
    projectId: 'contacts-app-b0616',
    authDomain: 'contacts-app-b0616.firebaseapp.com',
    storageBucket: 'contacts-app-b0616.firebasestorage.app',
    measurementId: 'G-X835H97L88',
  );

}